local:
	docker compose up -d && docker compose exec eo bash

pull:
	docker compose pull && docker compose up -d && docker compose exec eo bash

build:
	docker compose up --build -d && docker compose exec eo bash
